voxel_map:
  colors:
    new_obstacles:
      r: 0.0
      g: 0.8
      b: 0.8
      a: 1.0
    sure_obstacles:
      r: 0.0
      g: 0.7
      b: 0.3
      a: 1.0
    apriori_map:
      r: 0.0
      g: 0.5
      b: 0.0
      a: 1.0

    frontiers:
      r: 1.0
      g: 0.0
      b: 1.0
      a: 0.3
    candidates:
      r: 1.0
      g: 0.0
      b: 0.0
      a: 0.8
voxel_flags:
  colors:
    background:
      r: 0.0
      g: 0.7
      b: 0.3
      a: 1.0
    unknown:
      r: 0.1
      g: 0.3
      b: 0.7
      a: 1.0
